---
name: "Update sidebar on PR"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'wiki/**/*.md'  # Only trigger if wiki files change
      - '.github/scripts/generate_sidebar.py'  # Or if the script changes

permissions:
  contents: write
  pull-requests: write

jobs:
  update-sidebar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}  # Checkout the PR branch
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate sidebar
        run: python3 .github/scripts/generate_sidebar.py --wiki-dir wiki

      - name: Check for changes
        id: check-changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected in sidebar"
            git status --porcelain
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          fi

      - name: Commit and push changes
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add wiki/_Sidebar.md
          git commit -m "chore: auto-update sidebar"
          git push